<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>CbmrWebAdmin.ServerBinding</AssemblyName>
        <RootNamespace>CbmrWebAdmin.ServerBinding</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="CCB">
        <HintPath>..\CCB.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="11.0.0-preview.7.26381.103" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

</Project>
